# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    session.memcached:
        class: Memcached
        arguments:
            persistent_id: %session_memcache_prefix%
        calls:
            - [ addServer, [ %session_memcache_host_1%, %session_memcache_port_1% ]]
            #- [ addServer, [ %session_memcache_host_2%, %session_memcache_port_2% ]]

    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: ['@session.memcached', { prefix: %session_memcache_prefix%, expiretime: %session_memcache_expire% }]

